# Generated by Django 3.1.7 on 2021-03-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
